[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.2.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.5",
    "langchain-docling>=2.0.0",
    "langchain-ollama>=1.0.1",
    "langchain-text-splitters>=1.1.0",
    "streamlit>=1.52.2",
]
